import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CustomNavbar from "@/components/Navbar";
import CustomSidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const menu = [{path:"/", name:"Home"},{path:"/edit",name:"Our Blog"}]

  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomNavbar menu={menu}/>
        <div className="flex">
          <div className="hidden lg:block bg-gray-800 text-white w-64 h-full min-h-screen p-4">
            <nav className="mt-4">
              {menu.map((item, index) => (
                <a key={index} href={item.path} className="block px-4 py-2 rounded-md hover:bg-gray-700">
                  {item.name}
                </a>
              ))}
            </nav>
          </div>
          <div className="flex-1 p-4 bg-white min-h-screen">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
